-- Pontos de entrada idempotentes para operações críticas (a expansão de tipos fica em migrations futuras).
create or replace function public.submit_sync_command(p_id uuid,p_business_id uuid,p_device_id uuid,p_sequence bigint,p_type text,p_payload jsonb,p_occurred_at timestamptz)
returns public.sync_commands language plpgsql security definer set search_path=public,auth as $$ declare c public.sync_commands; begin
 perform public.assert_write_access(p_business_id); select * into c from public.sync_commands where id=p_id; if found then return c; end if;
 insert into public.sync_commands(id,business_id,user_id,device_id,device_sequence,command_type,payload_version,payload,occurred_at,status,attempt_count,last_attempt_at,processing_started_at,processing_expires_at) values(p_id,p_business_id,auth.uid(),p_device_id,p_sequence,p_type,1,p_payload,p_occurred_at,'processing',1,now(),now(),now()+interval '5 minutes') returning * into c; return c; end $$;
create or replace function public.record_sale(p_business_id uuid,p_sale_id uuid,p_channel public.sale_channel,p_source_location_id uuid,p_partner_id uuid,p_occurred_at timestamptz,p_items jsonb,p_device_id uuid,p_command_id uuid,p_offline_concurrent boolean default false)
returns uuid language plpgsql security definer set search_path=public,auth as $$ declare x jsonb; item_id uuid; begin
 perform public.assert_write_access(p_business_id); insert into public.sales(id,business_id,sale_channel,source_location_id,partner_point_id,occurred_at,recorded_by,device_id,command_id) values(p_sale_id,p_business_id,p_channel,p_source_location_id,p_partner_id,p_occurred_at,auth.uid(),p_device_id,p_command_id);
 for x in select value from jsonb_array_elements(p_items) loop item_id=coalesce((x->>'id')::uuid,gen_random_uuid()); insert into public.sale_items(id,business_id,sale_id,product_id,quantity,suggested_unit_price_cents,unit_price_cents,total_amount_cents,price_source) values(item_id,p_business_id,p_sale_id,(x->>'product_id')::uuid,(x->>'quantity')::integer,coalesce((x->>'suggested_unit_price_cents')::bigint,(x->>'unit_price_cents')::bigint),(x->>'unit_price_cents')::bigint,(x->>'quantity')::integer*(x->>'unit_price_cents')::bigint,coalesce(x->>'price_source','manual')); perform public.apply_stock_movement(p_business_id,(x->>'product_id')::uuid,p_source_location_id,null,(x->>'quantity')::integer,case when p_channel='direct' then 'direct_sale' else 'partner_sale' end,'sale',p_sale_id,item_id,p_occurred_at,p_device_id,p_command_id,p_offline_concurrent); end loop; update public.sync_commands set status=case when exists(select 1 from public.sync_conflicts where command_id=p_command_id and status='open') then 'conflict' else 'accepted' end,processed_at=now() where id=p_command_id; return p_sale_id; end $$;
revoke all on function public.submit_sync_command(uuid,uuid,uuid,bigint,text,jsonb,timestamptz),public.record_sale(uuid,uuid,public.sale_channel,uuid,uuid,timestamptz,jsonb,uuid,uuid,boolean) from public;
grant execute on function public.submit_sync_command(uuid,uuid,uuid,bigint,text,jsonb,timestamptz),public.record_sale(uuid,uuid,public.sale_channel,uuid,uuid,timestamptz,jsonb,uuid,uuid,boolean) to authenticated;
create or replace function public.resolve_stock_conflict(p_conflict_id uuid,p_adjustment_quantity integer,p_note text)
returns void language plpgsql security definer set search_path=public,auth as $$ declare c public.sync_conflicts; loc uuid; begin select * into c from public.sync_conflicts where id=p_conflict_id for update; perform public.assert_write_access(c.business_id,true); loc:=(c.server_summary->>'location_id')::uuid; if c.conflict_type<>'negative_stock' or c.status='resolved' or p_adjustment_quantity<=0 then raise exception 'invalid_conflict_resolution'; end if; perform public.apply_stock_movement(c.business_id,c.entity_id,null,loc,p_adjustment_quantity,'adjustment','conflict_resolution',c.id,null,now(),null,c.command_id,false); if exists(select 1 from public.stock_balances where business_id=c.business_id and product_id=c.entity_id and stock_location_id=loc and confirmed_quantity<0) then raise exception 'adjustment_does_not_resolve_negative_stock'; end if; update public.stock_balances set conflict_open=false where business_id=c.business_id and product_id=c.entity_id and stock_location_id=loc; update public.sync_conflicts set status='resolved',resolution_type='inventory_adjustment',resolution_operation_id=c.id,resolved_by=auth.uid(),resolved_at=now(),updated_at=now() where id=c.id; end $$;
revoke all on function public.resolve_stock_conflict(uuid,integer,text) from public;
grant execute on function public.resolve_stock_conflict(uuid,integer,text) to authenticated;
